name: Docker Image CI


on:
  workflow_dispatch: 
       inputs:
          environment:
            type: environment  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: User selections
      run: echo "user selected environment  ${{ github.event.inputs.environment }}"

    - name: Checkout
      uses: actions/checkout@v4

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker User login
      run: |
       docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

          
    - name: Build the Docker image
      run: |
       docker build . --tag swapnilak/nextjs-project1:$(date +%s)
       docker push swapnilak/nextjs-project1:$(date +%s)
