name: Docker Image CI
on:
  workflow_dispatch: 
       inputs:
          image-tag:
            type: text
            required: true
            description: please enter image tag name
          environment:
            type: environment  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        shell: bash
        
    steps:
    - name: User selections
      run: echo "user selected environment  ${{ github.event.inputs.environment }}"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

          
    - name: Build the Docker image
      run: | 
       docker build . --tag swapnilak/nextjs-project1:${{ github.events.inputs.image-tag }}
       docker push swapnilak/nextjs-project1:${{ github.events.inputs.image-tag }}
